// <auto-generated />
namespace Libra.Dal.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Issue_Name_Modifyied : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Issue_Name_Modifyied));
        
        string IMigrationMetadata.Id
        {
            get { return "202405240608355_Issue_Name_Modifyied"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
